#!/usr/bin/env bash

printf 'compiling ... \n'
javac Event.java Sim.java

printf 'compilation successful\nrunning simulation ...\n'

rm -f /output
java Simulation "./config.txt" >> output

printf 'simulation finished\n'
